services:
  postgres:
    image: postgres:18
    container_name: aviator-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: aviator
      POSTGRES_USER: aviator
      POSTGRES_PASSWORD: aviator_password

    ports:
      - "5434:5432"

    volumes:
      - aviator_postgres_data:/var/lib/postgresql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aviator-backend
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_URL: postgres://aviator:aviator_password@postgres:5432/aviator?sslmode=disable

    ports:
      - "7000:7000"

    depends_on:
      - postgres

volumes:
  aviator_postgres_data: